---
title: "Resultatforskjeller mellom Jobbsjansen og introduksjonsprogrammet"
description: |
  På oppdrag fra IMDi sammenlikna vi resultatene i Jobbsjansen og Introduksjonsprogrammet.
author:
  - name: Eivind Hageberg
    url: https://suppe-og-analyse.netlify.app
date: 2023-01-13
output:
  distill::distill_article:
    self_contained: false
---

*Rapporten er publisert [her](https://ideas2evidence.com/sites/default/files/Resultatforskjeller%20mellom%20Jobbsjansen%20og%20introduksjonsprogrammet.pdf). Her er sammendraget:*

Denne rapporten handler om resultatforskjellene mellom de to integrerings- og kvalifiseringsordningene Jobbsjansen og introduksjonsprogrammet. Det har tradisjonelt vært mange likhetstrekk mellom de to ordningene i både omfang, tiltaksbruk og hvilke målsetninger man har for dem som deltar. Samtidig har det vært en del forskjeller mellom deltakerne i de to ordningene, og overordnet sett kan en si at Jobbsjansen har hatt en deltakergruppe med bedre forutsetninger for å nå målene om overgang til arbeid eller utdanning. Over flere år har da også andelen deltakere som
oppnår overgang til arbeid eller utdanning direkte etter avsluttet deltakelse vært om lag 20 prosentpoeng høyere i Jobbsjansen.

Den sentrale problemstillingen for dette prosjektet har derfor vært å undersøke hvorvidt det er reelle forskjeller i resultatoppnåelsen mellom introduksjonsprogrammet og Jobbsjansen, når man tar høyde for ulikhetene i deltakersammensetningen. I arbeidet med denne og tilstøtende problemstillinger har vi basert oss på statistiske analyser av deltaker-, kommune- og prosjektdata. Vi har også gjennomført kvalitative case-studier i flere kommuner som tilbyr både Jobbsjansen og introduksjonsprogram. 

Vi finner gjennomgående at deltakelse i Jobbsjansen har en statistisk positiv betydning for en persons sannsynlighet for å gå over i jobb eller utdanning direkte etter fullført program. Dette gjelder selv når vi kontrollerer for deltakersammensetning, tar hensyn til kommunal kontekst og ressursforskjeller mellom ordningene. Hvor stor betydningen av Jobbsjansen er, varierer med hvilke deltakere vi snakker om, og hvilke statiske analysemetoder vi benytter. For en gjennomsnittlig «typisk» deltaker som kunne deltatt i begge ordninger, utgjør forskjellen om lag 11 prosentpoeng. Det vil si at for to personer som er helt like på egenskaper vi kan observere, så er sannsynligheten for å gå over i jobb eller utdanning etter fullført Jobbsjansen-prosjekt 11 prosentpoeng høyere enn etter fullført introduksjonsprogram. 

Jobbsjansen har altså en betydning, men generelt finner vi at den viktigste kilden til variasjon i måloppnåelse er de enkelte individenes forutsetninger, ikke hvilken ordning man tilhører, kjennetegn ved prosjektene eller den kommunale konteksten prosjektene befinner seg i. Samtidig viser det seg at det er et handlingsrom for den enkelte kommune og prosjekt til å påvirke resultatene. Det gjelder både i introduksjonsprogrammet og i Jobbsjansen. Vi beregner bidragsindikatorer for hver enkelt kommune og hvert enkelt prosjekt, som viser at noen prosjekter oppnår resultater som er mer enn 20 prosentpoeng over det som er forventet for deres deltakergruppe. Andre oppnår resultater 20 prosentpoeng under det som er forventet. Vi ser særlig forskjeller i prosjektenes bidrag hos personer med liten eller ingen skolegang og lavere norskferdigheter. Introduksjonsprogrammene gjør det jevnt over svakere for denne gruppen, enn det man statistisk sett kunne forvente. 

Gjennom analyser på både individ-, kommune- og prosjektnivå, gir rapporten ytterligere innsikt i hva som påvirker måloppnåelsen i de to ordningene.

På individnivået finner vi at en deltaker med gode norskferdigheter, høyt utdanningsnivå, lite fravær etc., har klart høyere sannsynlighet for å være i arbeid eller utdanning etter fullført program enn deltakere med mindre gode norskferdigheter, liten eller ingen utdanning fra før av eller høyt fravær. Vi finner ingen betydning av varigheten på programmet eller en persons botid på sannsynligheten for måloppnåelse. 

Tiltaksbruk har også betydning. Arbeidspraksis i ordinær virksomhet bidrar tydelig til økt sannsynlighet for måloppnåelse. Det samme gjør ordinært arbeid. Det er også flere tiltak som vi finner gir lavere sannsynlighet for måloppnåelse. Eksempler er helsefremmende aktiviteter og tiltak knyttet til barn og familie. Vi poengterer i rapporten at det ikke nødvendigvis er tiltakene i seg selv som har en negativ virkning. Det kan like godt handle om at deltakerne som trenger disse tiltakene, står lenger unna arbeid og videregående utdanning enn det ellers like deltakere gjør. 

På kommune- og prosjektnivå finner vi blant annet at deltakere i kommuner med høyere andel innvandrere i befolkningen har høyere sannsynlighet for måloppnåelse. Det kan tyde på at mer erfaring med integrering og innvandring i kommunene har positiv betydning. Videre finner vi at deltakere i kommuner med høyere nettoinnflytting har høyere sannsynlighet for måloppnåelse. Det kan bety at kommuner med bedre arbeidsmarked har det enklere med å få deltakere over i jobb. Vi finner også at ressurser har noe å si. Deltakere i prosjekter med høyere lønnsutgifter per deltaker har høyere sannsynlighet for overgang til arbeid eller utdanning. Tidligere forskning har vist at et begrenset antall deltakere pr rådgiver gjør det enklere å finne individuelle tilpasninger. Vi antar at dette har med kapasiteten til de ansatte å gjøre. Færre deltakere per rådgiver gir de ansatte mer tid til å følge opp deltakere, arbeidsgivere og andre samarbeidspartnere. 

Et gjennomgående funn i denne rapporten er at mye ligger til rette for høyere måloppnåelse i Jobbsjansen. Kommunene som har Jobbsjansen-prosjekt har en gjennomsnittlig høyere andel innvandrere og høyere netto innflytting. I tillegg er lønnsutgiftene pr. deltaker jevnt over høyere i Jobbsjansen-prosjekt enn i introduksjonsprogrammene. På individnivå har deltakerne i Jobbsjansen et gjennomsnittlig høyere norsknivå enn i introduksjonsprogrammet, bedre norskferdigheter og opprinnelsessteder som er assosiert med høyere sannsynlighet for måloppnåelse. Selv om vi ikke
finner en signifikant betydning av botid i våre analyser, er denne høyere i Jobbsjansen. Når vi snakker med ledere og programrådgivere i de to ordningene, trekkes gjerne botid frem som en viktig forklaring på resultatforskjellene.

Disse faktorene bidrar til å forklare deler av forskjellene i måloppnåelse mellom de to ordningene, men forklarer ikke alt. Selv når vi kontrollerer for kommunal kontekst, økonomiske ressurser og deltakersammensetning, finner vi altså at deltakelse i Jobbsjansen fortsatt gir høyere sannsynlighet for jobb eller utdanning direkte etter avsluttet deltakelse. I rapporten trekker vi derfor frem andre forhold ved Jobbsjansen, som rammebetingelser, arbeidsmetodikk og samarbeidsrelasjoner, som mulige forklaringer.

Vi finner for det første at i kommunene som har både Jobbsjansen-prosjekt og introduksjonsprogram, har deltakere i Jobbsjansen høyere sannsynlighet for måloppnåelse, kontrollert for øvrige forhold. Det antyder at den kommunale konteksten er mindre viktig enn hvilke muligheter de ansatte har til å utnytte rammene de jobber innenfor. Informantene våre fra Jobbsjansen og introduksjonsprogrammet innad i samme kommune så gjerne forskjellig på mulighetene i det lokale arbeidsmarkedet. Vi tolker dette som at Jobbsjansens ressurser til å utnytte arbeidsmarkedet, knytte kontakter og samarbeide med arbeidsgivere er en viktig faktor. 

Videre påpeker vi at rammene for Jobbsjansen gir ordningen deltakere som står nærmere arbeidsmarkedet, enn det de gjør i introduksjonsprogrammet. Dette gjelder også utover de individuelle egenskapene som vi kontrollerer for. Et slikt eksempel som flere informanter trekker fram, er at Jobbsjansen er et frivillig tilbud, som er veldig etterspurt av deltakerne. Prosjektene har dermed enklere tilgang på de mest motiverte deltakerne. Introduksjonsprogrammet er på sin side et tilbud som deltakerne har både rett og plikt til å delta i. Man kan derfor forvente seg et litt mer blandet nivå på motivasjonen for deltakerne.

Vi påpeker i rapporten at det kan være problematisk å trekke en direkte linje mellom arbeidsmetodikk og samarbeidsrelasjoner for å forklare forskjellene mellom Jobbsjansen og introduksjonsprogrammet. Basert på intervju med en rekke ledere og programrådgivere i begge ordningene, kan det overordnet sett se ut som om mye gjøres likt. Men vi finner at Jobbsjansen utmerker seg ved å produsere svært gode resultater for deltakere med mindre gode forutsetninger i utgangspunktet: Både de reelle og de forventede resultatene for deltakere med høyt utdanningsnivå eller gode norskferdigheter er forholdsvis sammenlignbare mellom de to ordningene. Jobbsjansen har imidlertid langt bedre resultater hos deltakere med liten eller ingen utdanning og lavt norsknivå ved avsluttet deltakelse. Det er da interessant at bruken av ordinær arbeidspraksis er langt høyere i Jobbsjansen enn i introduksjonsprogrammet. Forskjellen i prioritering av arbeidspraksis gjelder også for deltakere med mindre gode forutsetninger. Dette er spesielt interessant fordi vi finner at deltakelse i arbeidspraksis har en signifikant positiv betydning på sannsynligheten for måloppnåelse. 

Det ser også ut til at Jobbsjansen klarer å ha et mer aktivt forhold til både samarbeidspartnere og potensielle arbeidsgivere for deltakerne, enn hva introduksjonsprogrammet klarer. Prosjektene med fungerende samarbeid peker på ledelsesforankring av samarbeidet, samlokalisering av enkelte
tjenester, tidlig oppstart av samarbeid om konkrete deltakere og konkrete kontaktpersoner hos samarbeidspartnerne, som viktige suksessfaktorer.